language: rust
before_install: rvm install 2.1.5 && gem install bundler && bundle install
script: rake compile && bundle exec ruby -Itest test/test_*.rb && rake build && gem install pkg/* && ruby -rrustdown -e 'Rustdown.to_html("lol **important**")'
