[package]
name = "rustdown"
version = "0.1.0"
authors = ["Jonas Schneider <mail@jonasschneider.com>"]

[lib]
crate-type = ["dylib"]
path = "rustdown.rs"

[dependencies]
libc = "0.2.2"
markdown = "0.1"
